### ISSUE TITLE
Use only iv column and not salt by default

### ISSUE THREAD

**Issue by ribose-jeffreylau** [riboseinc/rails-keyserver#18]
https://github.com/attr-encrypted/attr_encrypted#the-mode-option

Our dependency on `attr_encrypted` means this project should act on deprecations on `mode`s involving `salt`.

Since we haven't released any official versions, I think it's safe to directly remove mentions of `salt` in the code, _e.g._, `db/migrate/20180822000001_create_schema.rb`, without risking breakage of other people's production code.

**Comment by ronaldtse** [comment]
Agreed!
